package com.example.appdevproject26s.social.sharing

import retrofit2.Response
import retrofit2.http.Body
import retrofit2.http.DELETE
import retrofit2.http.GET
import retrofit2.http.POST
import retrofit2.http.Path

// generated by gemini

interface SharingApiService {

    // --- Routes Sharing ---

    @POST("sharing/routes")
    suspend fun shareRoute(
        @Body request: ShareRouteRequest
    ): Response<SharedRouteResponse>

    @GET("sharing/routes")
    suspend fun getRoutesSharedWithMe(): Response<List<SharedRouteResponse>>

    // --- Pins Sharing ---

    @POST("sharing/pins")
    suspend fun sharePin(
        @Body request: SharePinRequest
    ): Response<SharedPinResponse>

    @GET("sharing/pins")
    suspend fun getPinsSharedWithMe(): Response<List<SharedPinResponse>>

    // --- Location Sharing ---

    @POST("sharing/location")
    suspend fun shareLocation(
        @Body request: ShareLocationRequest
    ): Response<LocationShareResponse>

    @DELETE("sharing/location/{username}")
    suspend fun revokeLocationShare(
        @Path("username") username: String
    ): Response<Unit>

    @GET("sharing/location")
    suspend fun getMyLocationShares(): Response<List<LocationShareResponse>>
}