package com.example.appdevproject26s.social.sharing

// generated by gemini
class SharingRepository(
    private val apiService: SharingApiService
) {
    // --- Routes ---

    suspend fun shareRoute(routeId: Long, username: String): Result<SharedRouteResponse> {
        return runCatching {
            val response = apiService.shareRoute(ShareRouteRequest(routeId, username))
            response.body() ?: throw Exception("Failed to share route: ${response.code()}")
        }
    }

    suspend fun getRoutesSharedWithMe(): Result<List<SharedRouteResponse>> {
        return runCatching {
            val response = apiService.getRoutesSharedWithMe()
            response.body() ?: emptyList()
        }
    }

    // --- Pins ---

    suspend fun sharePin(pinId: Long, username: String): Result<SharedPinResponse> {
        return runCatching {
            val response = apiService.sharePin(SharePinRequest(pinId, username))
            response.body() ?: throw Exception("Failed to share pin: ${response.code()}")
        }
    }

    suspend fun getPinsSharedWithMe(): Result<List<SharedPinResponse>> {
        return runCatching {
            val response = apiService.getPinsSharedWithMe()
            response.body() ?: emptyList()
        }
    }

    // --- Location ---

    suspend fun shareLocation(username: String): Result<LocationShareResponse> {
        return runCatching {
            val response = apiService.shareLocation(ShareLocationRequest(username))
            response.body() ?: throw Exception("Failed to share location: ${response.code()}")
        }
    }

    suspend fun revokeLocationShare(username: String): Result<Unit> {
        return runCatching {
            val response = apiService.revokeLocationShare(username)
            if (!response.isSuccessful) {
                throw Exception("Failed to revoke location share: ${response.code()}")
            }
        }
    }

    suspend fun getMyLocationShares(): Result<List<LocationShareResponse>> {
        return runCatching {
            val response = apiService.getMyLocationShares()
            response.body() ?: emptyList()
        }
    }
}