package com.example.appdevproject26s.social.sharing

// generated by gemmeni
// --- Request DTOs ---

data class ShareRouteRequest(
    val routeId: Long,
    val username: String
)

data class SharePinRequest(
    val pinId: Long,
    val username: String
)

data class ShareLocationRequest(
    val username: String
)

// --- Response DTOs ---

data class SharedRouteResponse(
    val id: Long,
    val routeId: Long,
    val sharedWithUsername: String,
    val sharedAt: String // ISO-8601 Instant String
)

data class SharedPinResponse(
    val id: Long,
    val pinId: Long,
    val sharedWithUsername: String,
    val sharedAt: String // ISO-8601 Instant String
)

data class LocationShareResponse(
    val id: Long,
    val sharedWithUsername: String,
    val active: Boolean,
    val createdAt: String // ISO-8601 Instant String
)