package com.example.appdevproject26s.social.sharing

import org.maplibre.spatialk.geojson.Position

// generated by gemmeni
// --- Request DTOs ---

data class MapPin(
    val id: Long,
    val position: Position,
    val note: String?,
    val isMine: Boolean,
    val ownerId: Long? = null
)

data class ShareRouteRequest(
    val routeId: Long,
    val username: String
)

data class SharePinRequest(
    val pinId: Long,
    val username: String
)

data class ShareLocationRequest(
    val username: String
)

// --- Response DTOs ---

data class SharedRouteResponse(
    val id: Long,
    val routeId: Long,
    val sharedWithUsername: String,
    val sharedAt: String // ISO-8601 Instant String
)

data class SharedPinResponse(
    val id: Long,
    val pinId: Long,
    val sharedWithUsername: String,
    val sharedAt: String, // ISO-8601 Instant String
    val pin: PinResponse? = null
)

data class LocationShareResponse(
    val id: Long,
    val sharedWithUsername: String,
    val active: Boolean,
    val createdAt: String // ISO-8601 Instant String
)

// --- Pin Management DTOs ---

data class CreatePinRequest(
    val lat: Double,
    val lng: Double,
    val note: String? = null
)

data class PinResponse(
    val id: Long,
    val lat: Double,
    val lng: Double,
    val note: String?,
    val createdAt: String?
)